stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: medical-front
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: medical.maximemoreillon.com

containerization:
  stage: containerization
  script:
    # If docker registry password provided, attempt login
    - >
      if [ -z ${CONTAINER_REGISTRY_PASSWORD} ];
      then echo "CONTAINER_REGISTRY_PASSWORD not set, skipping login";
      else echo "${CONTAINER_REGISTRY_PASSWORD}" | docker login ${CONTAINER_REGISTRY} --username ${CONTAINER_REGISTRY_USERNAME} --password-stdin;
      fi
    # Copy env vars
    - cp ${ACCOUNT_NAMES} ./.env
    - cp ${ENV} ./.env.production
    # Building and pushing container image
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME}


deployment:
  stage: deployment
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
